### PR TITLE
finished

### PR DESCRIPTION
**Pull request by cjanse**
# Description

Please include a summary of the changes and the related issue. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # [CN-](https://jpt4.atlassian.net/browse/CN-)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

# Checklist:

- [x] Have you merged main into this branch and resolved any conflicts?
- [x] Have you updated any necessary documentation?
- [x] Have you successfully run tests with your changes locally?

### CODE REVIEW

**Comment by cjanse** [comment]
Ran tests by testing starting addresses:

1. 102 Calhoun Street
2. 102 Calhoun Drive
3. 102 Calhoun Avenue

There is one defect that it won't consistently finds the closest bus stop but will find one that is somewhat close

**Comment by johnpturner8** [comment]
Needs a description, not sure what all was implemented.
I was expecting this ticket would get a list of the closest bus stops, does it do that?

**Comment by cjanse** [comment]
Yes, it generates a list of the closest bus stops but it also finds the closest bus stop to the starting address

**Review by johnpturner8 — APPROVED** [review]
I think this is good to merge. You should be good to mark CN-14 and CN-15 as done too (subtasks of CN-5)

**Review by johnpturner8 — CHANGES_REQUESTED** [review]
Actually, the issue with not selecting the closest bus stop is pretty severe. For example, use Wyatt Ave as the starting location. I think we need to fix this before merging.

**Comment by cjanse** [comment]
Alright, lets move it to the next sprint

**Comment by cjanse** [comment]
Ran tests by testing starting addresses:

102 Calhoun Street
102 Calhoun Drive
102 Calhoun Avenue
210 Madren Center Drive

**Review by johnpturner8 — APPROVED** [review]
This looks good to me. 

Next time, please add a description to the pull request, so I know what functionality you have added.

**Pull request merged**
